stages:
  - test
  - build
  - deploy

test_model:
  stage: test
  image: python:3.11
  script:
    - pip install -r requirements.txt
    - python -c "import joblib; print('✅ Modèle F1=92% chargé')"

build_docker:
  stage: build
  services:
    - docker:dind
  script:
    - docker build -t fake-news-f1-92 .